#!/bin/sh
# script for cronjob to make simplified rate preformed output by columns
## using rate_coin_names
# it exist because rate --coins gives obsolete list of coins
# which gives less data then regular rate command. NOT rate WRAPPER FAULT!

CSCRDIR="${CSCRDIR:-"${HOME}/.cache/cscripts"}"
SCRIPTS="${SCRIPTS:-"${HOME}/source/scripts"}"
RATE_CACHE="${CSCRDIR}/rate/rate"
RATE_FORM="${CSCRDIR}/rate/rate_form"
RATE_NAMES="${SCRIPTS}/sh/rate/rate_coin_names"
RATE_WRAPPER="${SCRIPTS}/sh/rate/rate"

get_coins_data() {
    "$RATE_WRAPPER" -f '%c\t%p\t%H\t%h\t%m\t%r' -o "$1" -d '\n'
}

drc="$(date +%s --utc -r "$RATE_CACHE")"
drf="$(date +%s --utc -r "$RATE_FORM")"

[ "$1" = debug ] && debug=1 || debug=0

if [ "$drc" -ge "$drf" ] || [ "$debug" -eq 1 ]; then
    CRYPTO_LIST="$("$RATE_NAMES" | tr '\n' ',' | sed "s/,$//")"
    DATA="$(get_coins_data "$CRYPTO_LIST")"
    # sometimes we get lines like these:
    # 0         +           +    0     0
    DATA="$(echo "$DATA" | sed '/^0/d')" # delete lines starting with 0
    if [ "$debug" -eq 0 ]; then
        echo "$DATA" > "$RATE_FORM"
        FRMT="$(column -R 3,4,5 -t "$RATE_FORM")"
        FRMT="$(echo "$FRMT" | sed '/^0/d')" # delete lines starting with 0
        echo "$FRMT" > "$RATE_FORM"
    elif [ "$debug" -eq 1 ]; then
        echo "$DATA"
    fi
fi

