#!/bin/sh
# calculates profit - Percentage Increase for coin name $1

XDGCHCS="${XDG_CACHE_HOME:-"$HOME/.cache"}/cscripts"
DIR="${CSCRDIR:-$XDGCHCS}/rate_hist"

coin="$1"
[ -z "$coin" ] && echo "provide coin name as \$1. exit." && exit 1
jsonfile=$(find "$DIR" -type f -name "*$coin*" -iname "*buy*" | head -n1)
[ ! -r "$jsonfile" ] && exit 1 # silently exit without outputting anything

# get operation history data
coin=$(jq -r '.coin' "$jsonfile")
filled=$(jq -r '.filled' "$jsonfile")
total=$(jq -r '.total' "$jsonfile")

convert="${filled}${coin}"
total_online="$(rate -c "$convert" -f "%p")" # current online price

final="$total_online"; initial="$total"
# Percentage Increase formula:
# %increase = 100 * ((final-initial) / |initial|)
formula="100 * (${final}-${initial}) / ${initial}"
pInc="$(echo "$formula" | bc)"
printf "%d%%" "$pInc"
