#!/bin/bash
# get average crypto exchange rate for last ~5 min
CSCRDIR="${CSCRDIR:-"$HOME/.cache/cscripts"}"
CACHE="${CSCRDIR}/rate/rate"
RATE_PRE="${CSCRDIR}/rate/rate_pre"
RATE_POST="${CSCRDIR}/rate/rate_post"

OLDIFS="$IFS"
NL='
' # New Line

bname="$(basename "$0")"
USAGE=$(printf "%s" "\
Usage: $bname [OPTION...]
GENERAL OPTIONS
    -c, --convert   Convert and get sum of currencies, separated by (+/-) each
    -e, --exchange  Change exchange currency (default: usd)
    -k, --insecure  Use curl option (by default https is used without -k option)
    -n, --number    Number of currencies in a spreadsheet (default: 10)
    -t, --test      Activate url preview test mode
    -C, --color     Allow ANSI sequences for colored output, not only text data
OUTPUT ONLY OPTIONS
    -d, --delimiter Delimiter to use between coins (man echo -e sequences sup.)
    -f, --format    Format of output:
        %r rank | %c coin | %p price | %H ch24h | %h ch01h | %m mcap | %s spark
    printf format of fields:
        --Pr rank | --Pp price | --Ph change | --Pm mcap
    -o, --output    Get multiple coins data separated via ',' as a delimiter
        --Ec        Get colored emoji (unicode symbols) in ch24h & ch01h
        --Mp        Min price string length as int value, format starts to apply
HELP
    -h, --help      Display help
    -H, --help-full Display full help which obtained via curl
    --currencies    List of supported currencies with their full names
    --coins         List of supported cryptocurrencies with their full names
    --debug         Show debug messages
EXAMPLES
    $bname -c 1337usd -e eur
    $bname 1337usd to eur
    $bname 1337 usd in eur
    - Above examples are equal and are valid.
    $bname -c 1BTC-10ETH+100LTC
    $bname -o btc,eth,bch -f '%c:%p[%H]' -d '\\n'
")

at_path() { hash "$1" >/dev/null 2>&1 ;} # if $1 is found at $PATH -> return 0

intv() {
    # exit if $1 is not a valid int value
    case "$1" in
        0*)
            printf "(%s)\n%s\n" "$1" "^ unsupported number! exit."
            exit 10
        ;;
        ''|*[!0-9]*)
            printf "(%s)\n%s\n" "$1" "^ is not a valid number of int! exit."
            exit 11
        ;;
    esac
}

get_opt() {
    # Parse and read OPTIONS command-line options
    SHORT=c:Cd:e:kf:hHn:o:t
    LONG=convert:,color,coins,currencies,debug,delimiter:,Ec,exchange:,format:,help,insecure,help-full,Mp:,number:,output:,Ph:,Pm:,Pp:,Pr:,test,s2d
    OPTIONS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
    # PLACE FOR OPTION DEFAULTS
    mplen=3 # min price string length as int value
    printf_h="%2s"
    printf_m="%3.0f"
    printf_p="%.${mplen}g"
    printf_r="%2.0f"
    exchange="usd"
    format="%c:%p"
    delimiter=" "
    n_hardcoded_max=600 # current max available coins in table
    Ec=0
    color=0 # color mode 1=on
    debug=0 # debug mode 1=on
    s2d=0
    eval set -- "$OPTIONS"
    while true; do
        case "$1" in
        -c|--convert)
            shift
            special="$1"
            ;;
        -C|--color)
            color=1
            ;;
        -d|--delimiter)
            shift
            delimiter="$1"
            ;;
        -e|--exchange)
            shift
            exchange="$1"
            ;;
        -k|--insecure)
            insecure=( --insecure )
            ;;
        -f|--format)
            shift
            format="$1"
            ;;
        -h|--help)
            echo "$USAGE"
            exit 0
            ;;
        -H|--help-full)
            echo "$USAGE"
            echo "THE FOLLOWING IS OBTAINED USING CURL (EVERY TIME)"
            special=":help"
            ;;
        -n|--number)
            shift
            intv "$1"
            n="$1"
            [ "$n" -gt "$n_hardcoded_max" ] && n="$n_hardcoded_max"
            ;;
        -o|--output)
            shift
            output="$1"
            ;;
        -t|--test)
            test=1
            ;;
        --Ph)
            shift
            printf_h="$1"
            ;;
        --Pm)
            shift
            printf_m="$1"
            ;;
        --Pp)
            shift
            printf_p="$1"
            ;;
        --Pr)
            shift
            printf_r="$1"
            ;;
        --Ec)
            Ec=1
            ;;
        --Mp)
            shift
            intv "$1"
            mplen="$1"
            ;;
        --coins)
            special=":coins"
            ;;
        --currencies)
            special=":currencies"
            ;;
        --debug)
            debug=1
            ;;
        --s2d)
            s2d=1
            ;;
        --)
            shift
            break
            ;;
        esac
        shift
    done
}

parse_in() {
    get_opt "$@"
    argarray=("$@")
    argcount="${#argarray[@]}"
    stringarray="${argarray[*]}"
    # substring: if first arg starts without '-'...
    if [[ "$stringarray" != -* && $argcount -eq 1 ]]; then
            special="${argarray[0]}"
            color=1 # allow colored output
    elif [[ "$stringarray" =~ " in " || "$stringarray" =~ " to " ]]; then
        if [[ $argcount -eq 3 ]]; then
            special="${argarray[0]}"
            exchange="${argarray[2]}"
        elif [[ $argcount -eq 4 ]]; then
            special="${argarray[0]}${argarray[1]}"
            exchange="${argarray[3]}"
        else
            echo "[$argcount]:args"
            echo "I don't get it. exit"
            exit 1
        fi
    fi
}

get_defaults() {
    # essential defaults in order to work
    if [[ $color -eq 1 ]]; then
        num=${n:-10} # to get n coins or 10 default
        T='' # allow colored output
    else
        num=$n_hardcoded_max # to get all coins from table to parse
        T='T' # text only, no ANSI sequences
    fi
}

# shellcheck disable=SC2001 # See if you can use ${variable//search/replace} instead.
colored_change_emojis() {
    ch01h="$1"
    ch24h="$2"
    if [ "$S2D" ] && [[ $s2d -eq 1 ]]; then
        c_g="$(s2d -c green)"
        c_r="$(s2d -c red)"
        u_w='▲ ' && upW="^c${c_g}^${u_w}^d^"
        d_w='▼ ' && dwW="^c${c_r}^${d_w}^d^"
        u_h=' ' && upH="^c${c_g}^${u_h}^d^"
        d_h=' ' && dwH="^c${c_r}^${d_h}^d^"
        u_n=' ' && upN="^c${c_g}^${u_n}^d^"
        d_n=' ' && dwN="^c${c_r}^${d_n}^d^"
        u_l=' ' && upL="^c${c_g}^${u_l}^d^"
        d_l=' ' && dwL="^c${c_r}^${d_l}^d^"
    else
        upW='🟩'
        dwW='🟥'
        upH='🟢'
        dwH='🔴'
        upN='▲ '
        dwN='▼ '
        upL=' '
        dwL=' '
    fi
    cW=20
    cH=10
    cN=5

    # get only int number
    _24h=$(echo "$ch24h" | sed "s/+//; s/-//; s/%//" | xargs printf "%.*f\n" "0")
    _01h=$(echo "$ch01h" | sed "s/+//; s/-//; s/%//" | xargs printf "%.*f\n" "0")

    # 24
    if [[ $_24h -ge $cW ]]; then
        if [[ $ch24h == +* ]]; then
            ch24h=$(echo "$ch24h" | sed "s/+/$upW/g")
        elif [[ $ch24h == -* ]]; then
            ch24h=$(echo "$ch24h" | sed "s/-/$dwW/g")
        fi
    elif [[ $_24h -ge $cH ]]; then
        if [[ $ch24h == +* ]]; then
            ch24h=$(echo "$ch24h" | sed "s/+/$upH/g")
        elif [[ $ch24h == -* ]]; then
            ch24h=$(echo "$ch24h" | sed "s/-/$dwH/g")
        fi
    elif [[ $_24h -ge $cN ]]; then
        if [[ $ch24h == +* ]]; then
            ch24h=$(echo "$ch24h" | sed "s/+/$upN/g")
        elif [[ $ch24h == -* ]]; then
            ch24h=$(echo "$ch24h" | sed "s/-/$dwN/g")
        fi
    else
        if [[ $ch24h == +* ]]; then
            ch24h=$(echo "$ch24h" | sed "s/+/$upL/g")
        elif [[ "$ch24h" == -* ]]; then
            ch24h=$(echo "$ch24h" | sed "s/-/$dwL/g")
        fi
    fi
    # 01
    if [[ $_01h -ge $cW ]]; then
        if [[ $ch01h == +* ]]; then
            ch01h=$(echo "$ch01h" | sed "s/+/$upW/g")
        elif [[ $ch01h == -* ]]; then
            ch01h=$(echo "$ch01h" | sed "s/-/$dwW/g")
        fi
    elif [[ $_01h -ge $cH ]]; then
        if [[ $ch01h == +* ]]; then
            ch01h=$(echo "$ch01h" | sed "s/+/$upH/g")
        elif [[ $ch01h == -* ]]; then
            ch01h=$(echo "$ch01h" | sed "s/-/$dwH/g")
        fi
    elif [[ $_01h -ge $cN ]]; then
        if [[ $ch01h == +* ]]; then
            ch01h=$(echo "$ch01h" | sed "s/+/$upN/g")
        elif [[ $ch01h == -* ]]; then
            ch01h=$(echo "$ch01h" | sed "s/-/$dwN/g")
        fi
    else
        if [[ $ch01h == +* ]]; then
            ch01h=$(echo "$ch01h" | sed "s/+/$upL/g")
        elif [[ $ch01h == -* ]]; then
            ch01h=$(echo "$ch01h" | sed "s/-/$dwL/g")
        fi
    fi
}

rate_process() {
    # clean & hide | bars as columns
    # rank,coin,price,ch24h,ch01h,mcap,spark
    form_pre=$(tail -n +13 "$CACHE" | head -n -2 | sed '/├─/d' | column -t -H 1,3,5,7,9,11,13,15)
    echo "$form_pre" > "$RATE_PRE"
    # make everything inside one awk
    form_post=$(awk '
    {
        printf "%-10s %-15s", $1, $2;
        printf "\t";

        # len of price value in decimal format;
        dlen=length(sprintf("%d", $3));
        if (dlen > 2)
            printf "%d", $3;
        else if (dlen == 2)
            printf "%.2f", $3;
        else
            if ($3 <= 0.0001)
                printf "%.1e", $3;
            else
                printf "%.3f", $3;
        printf "\t\t\t";

        # add + to change % and format as decimal without % sign
        printf "%+d\t\t%+d", $4, $5;
        printf "\t\t";

        # only decimal of mcap + letter(BM)
        if (match($6, "B$"))
            printf "%dB", $6;
        else if (match($6, "M$"))
            printf "%dM", $6;
        else
            printf "%d", $6;
        printf "\t\t";

        printf "%-15s", $7;
        printf "\n";
    }' "$RATE_PRE" | column -t)
    echo "$form_post" > "$RATE_POST"
}

# shellcheck disable=SC2001 # See if you can use ${variable//search/replace} instead.
# shellcheck disable=SC2059 # Don't use variables in the printf format string.
get_form_out() {
    multiline="$1"
    IFS=',' read -ra array <<< "$output"
    for name in "${array[@]}"; do
        foundline=$(echo "$multiline" | tail -n +13 | grep -Fiw "$name" | sed 's/│ //g')
        rank=$(echo "$foundline" | awk '{print $1}' | awk '{printf "'"$printf_r"'", $1}')
        coin=$(echo "$foundline" | awk '{print $2}')
        price=$(echo "$foundline" | awk '{print $3}')
        int_price=$(echo "$price" | sed 's/[.].*$//')
        # if length <= min_length -> apply printf format
        if [[ ${#int_price} -le $mplen ]]; then
            price=$(echo "$price" | awk '{printf "'"$printf_p"'", $1}')
        else
            price=$(echo "$price" | sed 's/[.].*$//')
        fi
        ch24h=$(echo "$foundline" | awk '{gsub("%",""); print $4}' | sed 's/[.].*$//')
        ch01h=$(echo "$foundline" | awk '{gsub("%",""); print $5}' | sed 's/[.].*$//')
        mcap=$(echo "$foundline" | awk '{print $6}')
        mcap=$(echo "$mcap" | sed -E 's/([[:digit:]]+)(.$)/\1 \2/' | awk '{printf("'"$printf_m"'%1s", $1, $2)}')
        spark=$(echo "$foundline" | awk '{print $7}')

        # if not contains '-' -> add '+'
        [[ "$ch24h" != -* ]] && ch24h='+'"$ch24h"
        [[ "$ch01h" != -* ]] && ch01h='+'"$ch01h"

        ch24h=$(printf "$printf_h" "$ch24h")
        ch01h=$(printf "$printf_h" "$ch01h")

        if [[ $Ec -eq 1 ]] || [[ $s2d -eq 1 ]]; then
            colored_change_emojis "$ch01h" "$ch24h"
        fi

        frmt="$format"
        [[ "$format" =~ "%r" ]] && frmt=$(echo "$frmt" | sed -E 's/%r/'"$rank"'/g')
        [[ "$format" =~ "%c" ]] && frmt=$(echo "$frmt" | sed -E 's/%c/'"$coin"'/g')
        [[ "$format" =~ "%p" ]] && frmt=$(echo "$frmt" | sed -E 's/%p/'"$price"'/g')
        [[ "$format" =~ "%H" ]] && frmt=$(echo "$frmt" | sed -E 's/%H/'"$ch24h"'/g')
        [[ "$format" =~ "%h" ]] && frmt=$(echo "$frmt" | sed -E 's/%h/'"$ch01h"'/g')
        [[ "$format" =~ "%m" ]] && frmt=$(echo "$frmt" | sed -E 's/%m/'"$mcap"'/g')
        [[ "$format" =~ "%s" ]] && frmt=$(echo "$frmt" | sed -E 's/%s/'"$spark"'/g')
        out+="$frmt""$delimiter"
    done
    echo -e "$out"
}

get_date() {
    if [ -f "$CACHE" ]; then
        TABLE=$(cat "$CACHE")
        # clean date from possible ANSI sequences of colored cache text, +remove UTC
        tempd=$(tail -n 1 "$CACHE" | sed 's/\x1b\[[0-9;]*m//g; s/ UTC//')
        date=$(date --date="$tempd" +%s --utc)
        dateadd=$(echo "$date+300" | bc) # add N to date
        difference=$(echo "$dateadd-($(date +%s --utc))+1" | bc)
        if [[ $difference -gt 0 ]]; then
            if [[ $difference -lt 10 ]]; then
                [ "$debug" -eq 1 ] && notify-send "rate - sleep to sync:" "$difference sec"
                sleep "$difference"
            elif [[ $difference -lt 299 ]]; then
                [ "$debug" -eq 1 ] && notify-send "rate - sync difference:" "$difference sec"
            fi
        fi
    else
        [ "$debug" -eq 1 ] && notify-send "[rate]" "$CACHE\nDoes not exist, or not regular file -> exit."
        exit 1
    fi
}

get_n_lines() {
    multiline="$1"
    sumn=$(echo "11+$n*2" | bc)
    head=$(echo "$multiline" | head -n "$sumn")
    time="$(date --date=@"$date" +%R):loc. $(date --date=@"$date" +%R --utc):UTC"
    boxb=$(echo "$multiline" | grep -F '┌─' | tr '┌' '└' | tr '┬' '┴' | tr '┐' '┘')
    tail=$(echo "$multiline" | tail -n 1)
    echo -e "$head""\n$boxb""\n$time""\n$tail"
}

do_curl() {
    url="$1"
    TABLE=$(curl -sf "${insecure[@]}" "$url")
}

upd_cache() {
    url="$1"
    # if date now > cached date + N -> curl and upd cache
    if [[ $(date +%s --utc) -gt $dateadd && $color -eq 0 ]]; then
        do_curl "$url"
        # if last line is date UTC -> upd cache
        if [[ $(echo "$TABLE" | tail -n 1) =~ [0-9]{4}(.[0-9][0-9]){5}.[0-9]+.UTC ]]; then
            echo "$TABLE" > "$CACHE"
        else
            [ "$debug" -eq 1 ] && notify-send "last line of TABLE not date UTC"
        fi
        get_date
        [ "$debug" -eq 1 ] && notify-send "rate srv sync:" "$(date --date=@"$date" +%R):last $(date +%R):now"
    fi
}

main() {
    parse_in "$@"
    get_defaults
    BASE='https://'"$exchange"'.rate.sx/'"$special"
    URL="$BASE?qF$T&n=$num"
    [[ $test ]] && echo "$URL" && exit 0
    get_date
    upd_cache "$URL"

    # main
    if [[ $output ]]; then
        get_form_out "$TABLE"
    elif [[ $n && $color -eq 0 ]]; then
        get_n_lines "$TABLE"
    else
        do_curl "$URL"
        echo "$TABLE"
    fi
}

main "$@"
