#!/bin/sh
# get color or drawing by name and output as simple string

abs_dir_path="$(dirname "$(realpath "$0")")"
cpath="$abs_dir_path/.colors"
dpath="$abs_dir_path/.drawings"
[ ! -f "$cpath" ] && printf "%s: %s\n%s\n" "ERROR & EXIT" "not found file:" "$cpath" && exit 1
[ ! -f "$dpath" ] && printf "%s: %s\n%s\n" "ERROR & EXIT" "not found file:" "$dpath" && exit 1

# read into variable using 'Here Document' code block
read -d '' USAGE <<- EOF
Usage: $(basename "$0") [OPTION...]
OPTIONS
    -c, --color     Get color by name
    -d, --draw      Get drawing by name
    -h, --help      Display help
    -H, --memo      Display S2D MEMO
    -l, --list      List all/color/drawing names (takes:[ a/c/d ])
    -p, --prefix    Add prefix string to output
    -P, --postfix   Add postfix string to output
EOF

# read into variable using 'Here Document' code block
read -d '' S2D_MEMO <<- EOF
${BLD}S2D MEMO:${END}
^rx,y,w,h^  Draw a rectangle of width w and height h,
            with its top left corner at (x,y) relative the X drawing cursor.
^c#FF0000^  Set foreground color.
^b#55cdfc^  Set background color, only applies to text,
            use the ^r^ command to change the background while drawing.
^f<px>^     Forward the X drawing cursor by <px> pixel.
            Please bear in mind that you have to move the cursor enough
            to display your drawing (by the with of your drawing).
^d^         Reset colors to SchemeNorm.
^C<num>^    Set foreground color to terminal color 0-15.
^B<num>^    Set background color to terminal color 0-15.
^w^         Swaps the current foreground/background colors.
            Useful when drawing multiple rectangles on top of one another.
^v^         Save current color scheme to restore it later with the ^t^ tag.
^t^         Restores the last color scheme saved by the ^v^ tag.
EOF

clean_content() {
    # remove everything after // characters and empty lines with/without spaces
    cat "$1" | sed "s/[[:space:]]*\/\/.*$//g; /^[[:space:]]*$/d"
}

get_opt() {
    # Parse and read OPTIONS command-line options
    SHORT=c:d:hHl:p:P:
    LONG=color:,draw:,help,list:,memo,prefix:,postfix:
    OPTIONS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
    # PLACE FOR OPTION DEFAULTS
    eval set -- "$OPTIONS"
    while true; do
        case "$1" in
        -c|--color)
            shift
            color="$1"
            cc=$(clean_content "$cpath")
            out_c=$(echo "$cc" | awk "/$color/"' {print $NF}') # last column
            ;;
        -d|--draw)
            shift
            draw="$1"
            cc=$(clean_content "$dpath")
            out_d=$(echo "$cc" | grep "$draw") # TODO unfinished
            ;;
        -h|--help)
            echo "$USAGE"
            exit 0
            ;;
        -H|--memo)
            echo "$S2D_MEMO"
            exit 0
            ;;
        -l|--list)
            shift
            ccc=$(clean_content "$cpath" | awk '{$NF=""}1') # all columns except last
            ccd=$(clean_content "$dpath") # TODO unfinished
            case "$1" in
                c) echo "$ccc" ;;
                d) echo "$ccd" ;;
                *) echo "$ccc"; echo "$ccd" ;;
            esac
            exit 0
            ;;
        -p|--prefix)
            shift
            out_p="$1"
            ;;
        -P|--postfix)
            shift
            out_P="$1"
            ;;
        --)
            shift
            break
            ;;
        esac
        shift
    done
}

get_opt "$@"

# intentionally print all in one line
printf "%s" "$out_p"
printf "%s" "$out_c"
printf "%s" "$out_d"
printf "%s" "$out_P"
