#!/bin/sh
# invoke one of a man search scripts located inside file dir
abs_dir_path=$(dirname "$(realpath "$0")")
cd "$abs_dir_path" || exit
scripts=$(ls | grep -vw $(basename "$0")) # excluding this file itself
echo "$scripts" | dmenu -i -p 'choose man search script: ' | xclip -in
selection="$(xclip -out)"
script_path="$abs_dir_path"'/'"$selection"
# if script exist and executable -> execute
[ -x "$script_path" ] && "$script_path"
