#!/bin/sh
# search locally and open python doc man page in $MANPAGER
CACHE_DIR="$HOME"'/.cache/man/python/'
K_FILE="$CACHE_DIR"'keywords'
M_FILE="$CACHE_DIR"'modules'
T_FILE="$CACHE_DIR"'topics'
A_FILE="$CACHE_DIR"'all'

update_cache() {
    mkdir -p "$CACHE_DIR"
    python -m pydoc keywords | tail -n +3 | cut -d' ' -f1- --output-delimiter=$'\n' | awk NF \
        | sort > "$K_FILE" &
    python -m pydoc modules | tail -n +3 | cut -d' ' -f1- --output-delimiter=$'\n' | awk NF \
        | sort > "$M_FILE" &
    python -m pydoc topics | tail -n +3 | cut -d' ' -f1- --output-delimiter=$'\n' | awk NF \
        | sort > "$T_FILE" &
    wait
    #cat "$K_FILE" "$M_FILE" "$T_FILE" > "$A_FILE" &
    ## same
    ls "$CACHE_DIR"* | grep -vw 'all' | xargs -r cat > "$A_FILE" &
}

interactive() {
    # first arg
    items=$(ls -l "$CACHE_DIR" | awk '{print $9}' | awk NF)
    item=$(echo "$items" | dmenu -p 'enter item to subsearch:' -l 30)
    # substring
    case "$item" in
        "keywords")
            local cache=$(cat "$K_FILE")
        ;;
        "modules")
            local cache=$(cat "$M_FILE")
        ;;
        "topics")
            local cache=$(cat "$T_FILE")
        ;;
        "all")
            local cache=$(cat "$A_FILE")
        ;;
        *)
            exit 0
        ;;
    esac >/dev/null
    if [ -t 0 ]; then
        echo "$cache" | dmenu -i -p 'enter man page name: ' -l 30 | xargs -r -o python -m pydoc
    else
        echo "$cache" | dmenu -i -p 'enter man page name: ' -l 30 | xargs -r $TERMINAL -e python -m pydoc
    fi
}

main() {
    update_cache &
    interactive
}

main "$@"
