#!/bin/sh
# This script is the SUDO_ASKPASS variable, meaning that it will be used as a
# password prompt if needed. Get patched dmenu with (-P option) from LukeSmith.

dmenu -fn Monospace-8 -P -p "$1" <&- && echo
