#!/bin/sh
# select & set sound effects preset.
cache="$CSCRDIR/active_preset"
presets=$(easyeffects -p | sed "2d; s/Output Presets: //; s/,/\n/g")
chosen=$(echo "$presets" | dmenu -p 'select preset:' -i)
[ -z "$chosen" ] && exit 1 # exit if none chosen.
echo "$chosen" > "$cache" # update current preset name in cache file
easyeffects -l "$chosen"  # change preset (real)
# change at easyeffects GUI (only preset name)
gsettings set com.github.wwmm.easyeffects last-used-output-preset "$chosen"
