#!/bin/sh
# set WM_NAME (window title) of active/focused window

arg="$1"

fwid=$(xdotool getactivewindow) # get id of the active/focused window

silence="SILENCE"
# toggle add/remove silence string in window title
if [ "$arg" = "$silence" ]; then
    wm_name=$(xprop -id "$fwid" WM_NAME | cut -d '"' -f 2)
    case "$wm_name" in
	*"$silence"*)
        # remove silence from window title
        input="$(echo "$wm_name" | sed "s/ \[${silence}\]//g")"
        ;;
    *)
        # append silence to window title
        input="${wm_name} [${silence}]"
        ;;
    esac
elif [ -z "$arg" ]; then
    input=$(echo "" | dmenu -p "enter new window title:")
else
    wm_name=$(xprop -id "$fwid" WM_NAME | cut -d '"' -f 2)
    input=$(echo "" | dmenu -p "enter new window title:" -it "$wm_name ")
fi

[ -z "$input" ] || [ "$input" = "$wm_name" ] && exit 1 # exit if ESC pressed or input is empty.

# set new WM_NAME
xdotool set_window --name "$input" "$fwid"
