#!/bin/sh
# select songs from .loved_tracks file with dmenu & add using mpc to the queue
lt="$HOME/Music/.playlists/.loved_tracks"

# shortcut to open file in the default editor
if [ "$1" = "-e" ]; then
    "$TERMINAL" -e "$EDITOR" "$lt"
    exit 0
fi

raw_data=$(cat "$lt")

input=$(echo "$raw_data" | dmenu -p "[Shift-Enter] add all matched songs to queue: " -i -g 3 -l 50)
[ -z "$input" ] && exit 1 # exit if ESC pressed or input is empty.

# -F -> to treat special characters like brackets '[]' as simple string
match=$(echo "$raw_data" | grep -iF "$input")

allfound=""
OLDIFS="$IFS"
IFS='
' # set Internal Field Separator to new line
for line in $match; do
    artist=$(echo "$line" | sed "s/ - .*$//")
    title=$( echo "$line" | sed "s/^.* - //")
    found=$(mpc find Artist "$artist" Title "$title")
    allfound=$(printf "%s\n%s" "$allfound" "$found")
done
IFS="$OLDIFS" # restore

# sort & remove empty lines with/without spaces -> add to the end of the queue
echo "$allfound" | sort | sed "/^[[:space:]]*$/d" | mpc add
