#!/bin/sh

# Prints the current volume or 🔇 if muted.

# use $1 or $SINK0 env variable if empty
SINK="${1:-"$SINK0"}"

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer --sink "$SINK" -t ;;
	4) pamixer --sink "$SINK" --allow-boost -i 1 ;;
	5) pamixer --sink "$SINK" --allow-boost -d 1 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# substring in sink name
case "$SINK" in
    *"hdmi"*)
        mute="🔇 HDMI"
    ;;
    *)
        mute="🔇 MUTE"
    ;;
esac >/dev/null

[ $(pamixer --sink "$SINK" --get-mute) = true ] && echo "$mute" && exit

vol="$(pamixer --sink "$SINK" --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "$icon $vol%"

