#!/bin/sh

# Prints the current volume or 🔇 if muted.

# use $1 or $SINK0 env variable if empty
SINK="${1:-"$SINK0"}"

case $BLOCK_BUTTON in
	1) pamixer --sink "$SINK" -t ;;
	2) setsid -f "$TERMINAL" -e pulsemixer ;;
	4) pamixer --sink "$SINK" --allow-boost -i 10 ;;
	5) pamixer --sink "$SINK" --allow-boost -d 10 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Left click to mute.
- Middle click to open pulsemixer.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# substring in sink name
case "$SINK" in
    *"hdmi"*)
        mute="HDMI"
    ;;
    *)
        mute="MUTE"
    ;;
esac >/dev/null

vol="$(pamixer --sink "$SINK" --get-volume)"
if [ "$vol" -gt 99 ]; then
    space=''
    N=4
else
    space=' '
    N=3
fi

if [ "$(pamixer --sink "$SINK" --get-mute)" = "true" ]; then
    if [ "$S2D" ]; then
        red="$(s2d -c red)"
        vol="^c${red}^${mute}^d^"
    else
        vol="$mute"
    fi
    icon="🔇"
    space=''
elif [ "$vol" -gt "70" ]; then
    icon="🔊"
elif [ "$vol" -lt "30" ]; then
    icon="🔈"
else
    icon="🔉"
fi

printf "%s%""$N""s%s" "$icon" "$vol" "$space"
