#!/bin/sh
# Displays todays weather, precipitation chance (💧) and daily low and high.
# Intended for the status bar.

arg="5" # hardcoded signal, used to update dwmblocks
SIG=$(echo "34+$arg" | bc)
fold="[+]wttr"
file="$CSCRDIR/non_live_forecast"

get_def() {
    # if $1 or env variable doesn't exist - location by default is based on ip
    LOCATION="${1:-"$LOC0"}"
    weatherreport=$(curl -sf "https://wttr.in/$LOCATION")
}

main() {
    oneliner=$(curl -sf "https://wttr.in/$LOCATION?format=%c_%f_%P_%o")
    # replace chars and split by \t
    sp=$(echo "$oneliner" | tr -d ' |\n' | sed "s/_/\t/g")
    # trim insufficient and make single variable each
    c=$(echo "$sp" | awk '{print $1}') # Weather condition
    f=$(echo "$sp" | awk '{print $2}' | tr -d '+|C') # Temperature (Feels Like)
    P=$(echo "$sp" | awk '{print $3}' | tr -d 'hPa' | sed 's/.$/k/') # pressure kPa
    o=$(echo "$sp" | awk '{print $4}') # Probability of Precipitation (0=empty?)
    form="$c$f$P$o"
    r0=$(echo "$form" | tr -d '\n' | sed "s/;/.,/g")
    case "$r0" in
        *[Uu]nknown*) r0="[U]" ;;
    esac
    # Some very particular and terse stream manipulation.
    # 💧todays the maximum probability of precipitation
    r1=$(echo "$weatherreport" | sed '16q;d' | grep -wo "[0-9]*%" | sort -rn | sed "s/^//g;1q" | tr -d '\n' | sed "s/;/.,/g")
    case "$r1" in
        ''|*0%) r1="" ;;
        *) r1=" 💧$r1 " ;;
    esac
    # temp daily low - high
    r2=$(echo "$weatherreport" | sed '13q;d' | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print ""$1".."$2"°"}')
    # compose string & print
    printf "%s%s%s" "$r0" "$r1" "$r2"
}

write_to_file() {
    echo "$weatherreport" > "$file"
}

fold_elem() {
    last_line=$(tail -n 1 "$file")
    # toggle between fold/unfold
    if [ "$last_line" = "$fold" ]; then
        sed -i '$d' "$file" # remove last line
    else
        # write to end of a file
        echo "$fold" >> "$file"
    fi
}

case $BLOCK_BUTTON in
    1) write_to_file && setsid -f "$TERMINAL" -e less -Srf "$file" ;;
    2) fold_elem ; kill "-$SIG" "$(pidof dwmblocks)" ;;
    3) notify-send "🌈 Weather module" "\- Left click for full forecast.
- MMB fold/unfold $fold
💧: Todays maximum probability of rain/snow
Daily low - Daily high" ;;
    4) _LOC="$LOC0" ; kill "-$SIG" "$(pidof dwmblocks)" ;;
    5) _LOC="$LOC1" ; kill "-$SIG" "$(pidof dwmblocks)" ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

last_line=$(tail -n 1 "$file")
if [ "$last_line" = "$fold" ]; then
    echo "$fold"
else
    #LOC="${_LOC:-"$LOC0"}"
    LOC="${1:-"$_LOC"}"
    get_def "$LOC"
    main
fi

