#!/bin/sh
# wget all accepted files
accepted=${2:-""}
[ -z "$accepted" ] && echo "[\$2] accepted files filter is empty... exit." && exit 1
wget --no-config --hsts-file=$XDG_CACHE_HOME/wget-hsts -r -l1 --no-parent -A"$accepted" "$1"


