#!/bin/sh
# shortcut - [cd] stands for cd (cd to pasted dir)

MATCH=$(s "$1" --pass-through)
[ -f "$MATCH" ] && MATCH=$(dirname "$MATCH") # remove file from end of the path
printf "cd %s" "$MATCH" | xclip && $(sleep 1 && xdotool click 2 && xdotool key Return) &
