#!/bin/sh
# shortcut - [r] stands for ranger

MATCH="$(s "${*}")"
[ -n "$MATCH" ] || exit 0 # handle cancel input
[ -d "$MATCH" ] || MATCH="$(dirname "$MATCH")" # remove file from end of the path
exec ranger "$MATCH"
