#!/bin/sh
# pipe arguments $1..$N into clipboard and show clipboard content
printf "%s" "${*}" | sed "s/[ \t]*$//" | xclip -sel clip -in && \
    notify-send -t 3000 -u low "📋clip content:" "\n$(xclip -o -sel clip)"
