#!/bin/bash
# execute local npm package (with args)
# without adding to PATH env local ./node_modules/.bin
# exit 1 -> if 'node_modules/.bin' dir does not exist at cwd
# exit 2 -> if cmd is not executable or file does not exist

nbin="$(npm bin)"
[ ! -d "$nbin" ] && exit 1
path="$nbin/$1"
if [ -e "$path" ]; then
    # simply execute cmd with all args except $1 (because it's executable name)
    "$path" "${@:2}"
else
    if [ -f "$path" ]; then
        echo "'$path' file exist, but it is not executable!"
    else
        echo "'$path' file does not exist!"
    fi
    exit 2
fi
