#!/bin/sh
# pomodoro wrapper for rlwrap completion

POMODORO_HOME=${POMODORO_HOME:-"$HOME/Documents/Pomodoro"}
week=$(date +"week-%V-%Y.txt")
week_file="$POMODORO_HOME/$week"
todo_file="$POMODORO_HOME/TODO.txt"
hist="$RLWRAP_HOME/pomodoro_history"
export RLWRAP_FILTERDIR="$SCRIPTS/py/rlwrap_filter/"
filter_name="pomodoro_rlwrap_filter.py"

date_from_to='^.*\d\d:\d\d'
digits='\d+' # simple digits
#forget_hist_1='^\dm\w*' # 1m06,0m,3mfix etc.
#forget_hist_2='^.*\^\[' # ^[, key^[ etc.

# create files if they do not exist
[ ! -f "$week_file" ] && echo "" >> "$week_file"
[ ! -f "$todo_file" ] && echo "" >> "$todo_file"

# r - option adds junk characters into completion list at runtime -> after filter!
# that's why filter cannot remove them
rlwrap -ir \
    -z "$filter_name -a '$week_file' -a '$todo_file' -a '$hist' \
    -f '$week_file' -r '$date_from_to' -r '$digits'" pomodoro
